### ISSUE TITLE
Перевод: How to Panic in Rust

### ISSUE THREAD

**Issue by andreevlex** [rust-lang-ru/translations#34]
источник: https://www.ralfj.de/blog/2019/11/25/how-to-panic-in-rust.html

**Comment by funkill** [comment]
[Файл в репе](https://github.com/rust-lang-ru/translations/blob/master/originals/articles/2019-11-25-how-to-panic-in-rust.md), [Gitlocalize](https://gitlocalize.com/repo/2799/ru/originals/articles/2019-11-25-how-to-panic-in-rust.md)
