### ISSUE TITLE
Перевод: Learning Parser Combinators With Rust

### ISSUE THREAD

**Issue by andreevlex** [rust-lang-ru/translations#6]
Классная статья для понимания комбинаторных парсеров.
https://bodil.lol/parser-combinators/

**Comment by funkill** [comment]
https://github.com/ruRust/translations/tree/master/originals/articles/parser-combinators

https://gitlocalize.com/repo/2799/ru/originals/articles/parser-combinators/index.md

**Comment by funkill** [comment]
Перевод опубликован: https://habr.com/ru/post/469213/
